// Package main SKWTR IDE Backend
//
//	@title			SKWTR IDE API
//	@version		1.0
//	@description	Auth and Ollama proxy backend for the SKWTR IDE.
//
//	@contact.name	Glenn
//	@contact.url	https://skwtr.com
//
//	@host		api.apps.skwtr.com
//	@BasePath	/ide
//
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				JWT token. Format: "Bearer <token>"
package main

import (
	"encoding/json"
	"log"
	"net/http"
	"os"
	"strings"

	httpSwagger "github.com/swaggo/http-swagger"
	"golang.org/x/crypto/bcrypt"

	"skwtr-ide-backend/db"
	_ "skwtr-ide-backend/docs" // generated by swag init
	"skwtr-ide-backend/handlers"
	"skwtr-ide-backend/middleware"
)

func main() {
	db.Init()
	seedAdmin()

	mux := http.NewServeMux()

	// ── Docs ──────────────────────────────────────────────────────────────────
	mux.HandleFunc("/docs/", httpSwagger.WrapHandler)

	// ── Auth ──────────────────────────────────────────────────────────────────
	mux.HandleFunc("/v1/auth/login", handlers.Login)

	mux.Handle("/v1/auth/register",
		middleware.AdminOnly(http.HandlerFunc(handlers.Register)))

	mux.Handle("/v1/auth/users",
		middleware.AdminOnly(http.HandlerFunc(handlers.ListUsers)))

	mux.Handle("/v1/auth/users/",
		middleware.AdminOnly(http.HandlerFunc(handlers.DeleteUser)))

	// ── AI ────────────────────────────────────────────────────────────────────
	mux.Handle("/v1/ai/chat",
		middleware.Auth(http.HandlerFunc(handlers.Chat)))

	mux.Handle("/v1/ai/complete",
		middleware.Auth(http.HandlerFunc(handlers.Complete)))

	// ── Code execution ─────────────────────────────────────────────────────────
	mux.Handle("/v1/code/run",
		middleware.Auth(http.HandlerFunc(handlers.RunCode)))

	mux.Handle("/v1/code/languages",
		middleware.Auth(http.HandlerFunc(handlers.ListLanguages)))

	mux.Handle("/v1/code/status/",
		middleware.Auth(http.HandlerFunc(handlers.GetSubmissionStatus)))

	// ── Health ────────────────────────────────────────────────────────────────
	mux.HandleFunc("/v1/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	})

	addr := os.Getenv("ADDR")
	if addr == "" {
		addr = ":8080"
	}

	log.Printf("skwtr-ide-backend listening on %s", addr)
	log.Printf("swagger UI available at http://localhost%s/docs/", addr)

	if err := http.ListenAndServe(addr, corsMiddleware(mux)); err != nil {
		log.Fatalf("server error: %v", err)
	}
}

func seedAdmin() {
	username := os.Getenv("ADMIN_USERNAME")
	password := os.Getenv("ADMIN_PASSWORD")
	if username == "" || password == "" {
		log.Println("seed: ADMIN_USERNAME/ADMIN_PASSWORD not set, skipping")
		return
	}

	existing, err := db.GetUserByUsername(username)
	if err != nil {
		log.Fatalf("seed: db error: %v", err)
	}
	if existing != nil {
		log.Printf("seed: admin '%s' already exists, skipping", username)
		return
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		log.Fatalf("seed: failed to hash admin password: %v", err)
	}

	if _, err := db.CreateUser(username, string(hash), "admin"); err != nil {
		log.Fatalf("seed: failed to create admin: %v", err)
	}

	log.Printf("seed: admin '%s' created", username)
}

func corsMiddleware(next http.Handler) http.Handler {
	allowedOrigins := strings.Split(os.Getenv("CORS_ORIGINS"), ",")

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		origin := r.Header.Get("Origin")

		for _, o := range allowedOrigins {
			if strings.TrimSpace(o) == origin {
				w.Header().Set("Access-Control-Allow-Origin", origin)
				w.Header().Set("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
				w.Header().Set("Access-Control-Allow-Headers", "Authorization, Content-Type")
				w.Header().Set("Access-Control-Max-Age", "86400")
				break
			}
		}

		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}

		next.ServeHTTP(w, r)
	})
}
