// Code generated by swaggo/swag. DO NOT EDIT.
// Run `swag init` to regenerate this file.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "Auth and Ollama proxy backend for the SKWTR IDE.",
        "title": "SKWTR IDE API",
        "contact": {
            "name": "Glenn",
            "url": "https://skwtr.com"
        },
        "version": "1.0"
    },
    "host": "ide-api.apps.skwtr.com",
    "basePath": "/",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "ide-api.apps.skwtr.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SKWTR IDE API",
	Description:      "Auth and Ollama proxy backend for the SKWTR IDE.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
